# Generated by Django 4.0.3 on 2022-04-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kitobning nomi')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200, verbose_name='Muallifi')),
                ('publish_date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('buy_count', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='media/photo')),
                ('file_book', models.FileField(null=True, upload_to='media/files', verbose_name='Kitob fayli')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
